political:
  - DailyCurrent
  - DailyNews
  - ABCNews
  - Disclose
  - EmpireHerald
  - MSNBC
  - NationalReport
  - News Biscuit
  - Newslo
  - TheBostonTribune
  - NewsNerd
  - WND
  - WorldNews
  - WorldTruth
  - USAPremier
  - Chronicle
  - CBSNews
  - CityJournal
  - DailyNewsbin
  - Daily USA Update
  - FrontpageMag
  - GlobalEconomicAnalysis
  - GlobalPoliticsNow
  - GlossyNews
  - LifeNews
  - NationNews
  - NewsCorpse
  - NYmeta
  - PolicyReview
  - TheCivillian
  - InfoPoint
  - USANews
  - DailyTime
  - WashingtonExaminer
  - WorldDaily
  - YourNewsWire
  - Feedly
  - WealthWire
  - USLifeToday
  - WorldTimes
  - TheWashingtonPress
  - FreePress
  - TimesOfTheWorld
  - WorldStyle
  - PeoplesVoice
  - NewsCube
